title: Aru的修炼之路
author: Aru
email: aru_kju@163.com
description: > # this means to ignore newlines until "baseurl:"
  I will share my study experience of programming here~ 
  Welcome to communicate with me~

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  Aru-han # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima

